# Generated by Django 5.1.5 on 2025-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('TX1', models.IntegerField()),
                ('TX2', models.IntegerField()),
                ('TX3', models.IntegerField()),
                ('TX4', models.IntegerField()),
                ('ĐGGK', models.IntegerField()),
                ('ĐGCK', models.IntegerField()),
                ('ĐTB', models.IntegerField()),
            ],
        ),
    ]
