# Generated by Django 5.1.5 on 2025-02-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Score', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='ĐGCK',
        ),
        migrations.RemoveField(
            model_name='score',
            name='ĐGGK',
        ),
        migrations.RemoveField(
            model_name='score',
            name='ĐTB',
        ),
        migrations.AddField(
            model_name='score',
            name='DGCK',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='DGGK',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='DTB',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='TX1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='TX2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='TX3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='TX4',
            field=models.FloatField(),
        ),
    ]
